export const glossary = {
  hyperscaler: `A company that owns warehouse-scale computing hardware — the GPUs — and rents it out.`,
  compute: `Raw computing work supplied by hardware. Every AI answer consumes some; a hyperscaler's capacity is how much it can supply per period.`,
  flop: `A unit of raw computing work — one floating-point operation. Every standardized AI output uses an expected number of them, written a_m in the model.`,
  modelLaboratory: `A company that builds an AI model and sells its outputs. Kept distinct from the hyperscaler that owns the hardware.`,
  scarcity: `For the next several years, people want more AI output at near-cost prices than the installed hardware can produce. This is the paper's maintained assumption, not a claim that demand always exceeds capacity at every price.`,
  marginalValue: `What one more unit of compute would earn a firm, in dollars, given the compute it already has. It falls as the firm serves ever-less-eager customers.`,
  shadowPrice: `The rental price one unit of compute commands, in dollars, when there isn't enough to go around. In the allocation chart it is the height of the water line, written the Greek letter lambda.`,
  scarcityRent: `Earnings above the physical cost of running the hardware that exist only because capacity is limited, like the premium on the last few rooms in a full hotel.`,
  qualityAdjustedProductivity: `Value delivered per unit of compute, not per answer: a model giving better answers on half the compute scores twice as high. Written q = Q / a.`,
  winnerTakeMost: `Winner-take-all means one model gets literally every unit of compute. That needs a demanding condition — the leader's least valuable funded use must still beat the runner-up's most valuable use. Miss it and the market splits: winner-take-most, not all.`,
  markup: `The gap, in dollars, between the price and a firm's own all-in cost per unit, sustainable because the few competitors' products aren't perfect substitutes.`,
  cournot: `A model of competition among a few firms: each chooses how much to produce, knowing that flooding the market lowers the price for everyone, itself included. More firms means each holds back less, so prices fall. We use it because the AI model market has a handful of firms, not thousands.`,
  lernerIndex: `A gauge of pricing power: the markup as a fraction of price. It equals one over how price-sensitive the firm's customers are — hard-to-replace products mean insensitive customers and a big markup.`,
  nashBargaining: `A way to model a negotiated price: each side keeps its walk-away value, and the surplus left over is split according to bargaining strength.`,
  oligopsony: `Market power exercised by the buyers — a few big laboratories can push the rental price of compute down. It is the mirror image of ordinary seller power.`,
  bindingVsSlack: `Binding capacity: firms would happily sell more if the hardware existed — capacity is the bottleneck. Slack capacity: the bottleneck is gone, and any remaining premium is competitive strategy, not scarcity.`,
  opportunityCost: `What the compute would earn in its best alternative use, such as renting it to the leader. A firm can be cash-positive yet still burning value if its hardware is worth more to someone else.`,
  lossLeading: `Selling below your own cash cost on purpose, betting that staying in the game — keeping customers, data, know-how — pays off later. The paper formalizes when that bet is rational, and warns it should not be assumed.`,
  fixedCost: `A cost you pay once to show up, before selling anything. Here it's the compute to train a frontier model. It is sunk: once spent it's gone whether or not the model ever earns it back.`,
  naturalOligopoly: `When a market's fixed costs are large next to its total profit pool, only a few firms can ever break even in it, and sometimes only one (a natural monopoly). The count is set by how many firms can recover the fixed cost, not by who competes best once they are in.`,
  hazard: `The chance per period that an event occurs, such as a rival catching up. A catch-up hazard of 0.5 a year means a lead lasts about two years on average.`,
  valueFormula: `The worth of a temporary lead: profit-while-ahead divided by (interest rate + catch-up risk). Catch-up risk acts exactly like extra impatience — a lead that could end any month is worth far less than the same profits guaranteed.`,
  qualityLadder: `Economists' name for markets where firms leapfrog each other with better versions. Each leader's profits are both the prize that motivated the last innovation and the target of the next one — Schumpeter's "creative destruction."`,
  asymptote: `A ceiling the technology approaches but can't pass. A common ceiling means everyone eventually builds essentially the same-quality product; firm-specific ceilings mean some organizations can simply reach higher, permanently.`,
  commoditization: `When a product becomes interchangeable across suppliers and competition drives price down to cost. The key warning: equal quality alone doesn't do it — you also need enough competing model sellers AND enough hardware. Three conditions, not one.`,
  twoPartTariff: `Pay a flat fee for membership, then a low price per use — gyms and warehouse clubs work this way. The flat fee harvests value the per-use price leaves behind.`,
  multiHoming: `Keeping subscriptions to several providers and routing each task to whichever is best at it. A second-tier provider doesn't need to be anyone's favorite overall — just clearly better at something — to earn its fee.`,
  qualityAdjustedPrice: `Price per unit of usefulness rather than per answer. Nominal prices can stay flat while quality-adjusted prices collapse, and most of what users gain arrives this way.`,
  producerSurplus: `What sellers keep above the real cost of running the hardware: the scarcity rent plus the markup, split between the hyperscalers that own the chips and the laboratories that sell the output.`,
  deadweightLoss: `Value that simply disappears rather than changing hands — trades that should happen but don't. A transfer only moves money between parties; a deadweight loss is gone from everyone.`,
} as const

export type GlossaryTerm = keyof typeof glossary
